### ISSUE TITLE
ASE returns 401 (Invalid_Token error) - while onboarding autoscale NSD

### ISSUE THREAD

**Issue by onurko** [openbaton/autoscaling-engine#10]
Hello,

With given NSD example, NetworkServiceRecordRestAgent returns invalid_token error. I am attaching our sample NSD and autoscaling logs.
[sample_nsd.txt](https://github.com/openbaton/autoscaling-engine/files/1174246/sample_nsd.txt)
[autoscale.txt](https://github.com/openbaton/autoscaling-engine/files/1174252/autoscale.txt)

**Comment by gc4rella** [comment]
It seems the token requested by the ASE is expired. which ASE version are you running? It seems that you are spotting a bug which was fixed sometime ago. please provide more details about the scenario. did you restart the ASE? is the ASE running since a long time? 

In any case, I think that restarting the ASE should temporary fix your issue.

**Comment by onurko** [comment]
Hello,

The version of ASE is 1.2.2. The scenario is very straight-forward, just launch the given NSD with auto-scale policy and encounter the given error logs. Although i restarted ASE engine, faced same problem. Another problem occurs while deleting NSR from OpenBaton. The foreign keys should be deleted manually from all DB tables which are altered for autoscaling. This can be evaluated as another problem and we can open issue for that also.

Thanks.

**Comment by orkun34** [comment]
Is there any things going on about this issue ? 

I've same problem. Whenever I restart it works for a while then it throws same error which is related to "401 Unauthorized"

**Comment by gc4rella** [comment]
yes, we have introduced a new mechanism for integrating external components like the ASE. It is already available under develop branches, and we plan to release a major release by the end of the month. Be aware that this new mechanism won't be compatible with older versions of the NFVO, so you will need to upgrade the whole environment.

**Comment by mpauls** [comment]
shall be fixed by the introduction of the service mechanism
